ALTER TABLE `issue_tracker_activity_calender` ADD `title_punjabi` VARCHAR(500) NULL DEFAULT NULL AFTER `title`;
ALTER TABLE `issue_tracker_activity_calender` CHANGE `title_punjabi` `title_punjabi` VARCHAR(500) CHARACTER SET utf32 COLLATE utf32_unicode_ci NULL DEFAULT NULL;


INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Class room decoration with subject charts (Inter class Activity)','ਵਿਸ਼ਾ ਚਾਰਟ (ਇੰਟਰ ਕਲਾਸ ਗਤੀਵਿਧੀ) ਦੇ ਨਾਲ ਕਲਾਸ ਰੂਮ ਦੀ ਸਜਾਵਟ','Curricular Activities','2025-03-07',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter house Know your Country Quiz','ਇੰਟਰ ਹਾਊਸ ਆਪਣੇ ਦੇਸ਼ ਕਵਿਜ਼ ਨੂੰ ਜਾਣੋ','Curricular Activities','2025-03-14',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House Creative Writing Competition (English/Hindi/Punjabi to write on Current issues in India with solutions)','ਅੰਤਰ-ਹਾਊਸ ਰਚਨਾਤਮਕ ਲੇਖਣ ਮੁਕਾਬਲਾ (ਭਾਰਤ ਦੇ ਮੌਜੂਦਾ ਮੁੱਦਿਆਂ ''ਤੇ ਹੱਲਾਂ ਦੇ ਨਾਲ ਲਿਖਣ ਲਈ ਅੰਗਰੇਜ਼ੀ/ਹਿੰਦੀ/ਪੰਜਾਬੀ)','Curricular Activities','2025-03-21',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Talent hunt','ਪ੍ਰਤਿਭਾ ਦੀ ਖੋਜ','Curricular Activities','2025-03-28',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter house Dastar Bandi Competition (Sunday, 7- pm to 8 pm)','ਅੰਤਰ ਹਾਊਸ ਦਸਤਾਰ ਬੰਦੀ ਮੁਕਾਬਲਾ (ਐਤਵਾਰ, ਸ਼ਾਮ 7 ਵਜੇ ਤੋਂ ਰਾਤ 8 ਵਜੇ ਤੱਕ)','Curricular Activities','2025-03-30',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Grooming Week.','ਸ਼ਿੰਗਾਰ ਹਫ਼ਤਾ।','Curricular Activities','2025-03-22',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Ground Activity: Friendly match of Football, Basket Ball, Volley ball','ਗਰਾਊਂਡ ਗਤੀਵਿਧੀ: ਫੁੱਟਬਾਲ, ਬਾਸਕਟ ਬਾਲ, ਵਾਲੀਬਾਲ ਦਾ ਦੋਸਤਾਨਾ ਮੈਚ','Curricular Activities','2025-04-04',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House Vocabulary Hunt & Word Wall creation Competition (English/Punjabi /Hindi)','ਅੰਤਰ-ਹਾਊਸ ਸ਼ਬਦਾਵਲੀ ਹੰਟ ਅਤੇ ਸ਼ਬਦ ਕੰਧ ਨਿਰਮਾਣ ਮੁਕਾਬਲਾ (ਅੰਗਰੇਜ਼ੀ/ਪੰਜਾਬੀ/ਹਿੰਦੀ)','Curricular Activities','2025-04-11',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Religious Programme: Baisakhi : Inter Class Poetry recitation competition  (Punjabi)','ਧਾਰਮਿਕ ਪ੍ਰੋਗਰਾਮ: ਵਿਸਾਖੀ: ਅੰਤਰ ਜਮਾਤੀ ਕਵਿਤਾ ਪਾਠ ਮੁਕਾਬਲਾ (ਪੰਜਾਬੀ)','Curricular Activities','2025-04-13',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Oath ceremony by Student Council VIII-XII','ਸਟੂਡੈਂਟ ਕੌਂਸਲ ਅੱਠਵੀਂ-ਬਾਰ੍ਹਵੀਂ ਵੱਲੋਂ ਸਹੁੰ ਚੁੱਕ ਸਮਾਗਮ','Curricular Activities','2025-04-18',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Language appreciation week','ਭਾਸ਼ਾ ਦੀ ਪ੍ਰਸ਼ੰਸਾ ਹਫ਼ਤਾ','Curricular Activities','2025-04-19',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter class slogan writing competition. (Theme: Save Energy Save resources)','ਅੰਤਰ ਕਲਾਸ ਸਲੋਗਨ ਲਿਖਣ ਮੁਕਾਬਲਾ (ਥੀਮ: ਊਰਜਾ ਬਚਾਓ ਸਰੋਤ ਬਚਾਓ)','Curricular Activities','2025-04-25',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Ground Activity: Friendly match of Football, Basket Ball, Volley ball','ਗਰਾਊਂਡ ਗਤੀਵਿਧੀ: ਫੁੱਟਬਾਲ, ਬਾਸਕਟ ਬਾਲ, ਵਾਲੀਬਾਲ ਦਾ ਦੋਸਤਾਨਾ ਮੈਚ','Curricular Activities','2025-05-02',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PCM for Nursery – VI (Girls & Boys)','ਨਰਸਰੀ ਲਈ PCM - VI (ਲੜਕੀਆਂ ਅਤੇ ਲੜਕੇ)','Curricular Activities','2025-04-06',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PCM for VII-IX(Boys)','VII-IX (ਲੜਕੇ) ਲਈ PCM','Curricular Activities','2025-04-13',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PCM for VII-IX(Girls)','VII-IX (ਲੜਕੀਆਂ) ਲਈ PCM','Curricular Activities','2025-04-20',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PCM for X-XII(Boys)','X-XII (ਲੜਕੇ) ਲਈ PCM','Curricular Activities','2025-04-27',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House Maths  Quiz Competition','ਅੰਤਰ ਹਾਊਸ ਗਣਿਤ ਕੁਇਜ਼ ਮੁਕਾਬਲਾ','Curricular Activities','2025-05-01',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PCM for X-XII(Girls)','X-XII (ਲੜਕੀਆਂ) ਲਈ PCM','Curricular Activities','2025-05-04',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Pre-Midterm Examination','ਪ੍ਰੀ-ਮਿਡਟਰਮ ਪ੍ਰੀਖਿਆ','Curricular Activities','2025-05-06',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Religious  Programme: Prakash purab of Shri Guru Amar Das Dev Ji Inter house Shabad Gayan and Sakhi telling competition','ਧਾਰਮਿਕ ਪ੍ਰੋਗਰਾਮ: ਸ਼੍ਰੀ ਗੁਰੂ ਅਮਰਦਾਸ ਦੇਵ ਜੀ ਦੇ ਪ੍ਰਕਾਸ਼ ਪੁਰਬ ਸਬੰਧੀ ਅੰਤਰ-ਘਰ ਸ਼ਬਦ ਗਾਇਣ ਅਤੇ ਸਾਖੀ ਸੁਣਾਉਣ ਦੇ ਮੁਕਾਬਲੇ','Curricular Activities','2025-05-11',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House Science Quiz','ਇੰਟਰ ਹਾਊਸ ਸਾਇੰਸ ਕਵਿਜ਼','Curricular Activities','2025-05-23',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PTM for for Nursery – V (Girls & Boys)','ਨਰਸਰੀ ਲਈ PTM - V (ਲੜਕੀਆਂ ਅਤੇ ਲੜਕੇ)','Curricular Activities','2025-05-24',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Club Activity: Peace Walk-a thon, Peace Wall, TED talks','ਕਲੱਬ ਗਤੀਵਿਧੀ: ਪੀਸ ਵਾਕ-ਏ ਥੋਨ, ਪੀਸ ਵਾਲ, ਟੀਈਡੀ ਗੱਲਬਾਤ','Curricular Activities','2025-05-26',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House Poster Making Competition on Safety','ਸੁਰੱਖਿਆ ਸਬੰਧੀ ਅੰਤਰ ਹਾਊਸ ਪੋਸਟਰ ਮੇਕਿੰਗ ਮੁਕਾਬਲਾ','Curricular Activities','2025-05-26',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter class Wall Magazine Competition','ਅੰਤਰ ਕਲਾਸ ਵਾਲ ਮੈਗਜ਼ੀਨ ਮੁਕਾਬਲਾ','Curricular Activities','2025-05-26',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Religious Programme : Martyrdom of Guru Arjun Dev Ji','ਧਾਰਮਿਕ ਪ੍ਰੋਗਰਾਮ: ਗੁਰੂ ਅਰਜਨ ਦੇਵ ਜੀ ਦੀ ਸ਼ਹੀਦੀ','Curricular Activities','2025-05-30',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House Gurmat Quiz & Sukhmani Sahib recitation','ਅੰਤਰ ਹਾਊਸ ਗੁਰਮਤਿ ਕੁਇਜ਼ ਅਤੇ ਸੁਖਮਨੀ ਸਾਹਿਬ ਦਾ ਪਾਠ','Curricular Activities','2025-05-30',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Ground Activity: Friendly match of Football, Basket Ball, Volley ball','ਗਰਾਊਂਡ ਗਤੀਵਿਧੀ: ਫੁੱਟਬਾਲ, ਬਾਸਕਟ ਬਾਲ, ਵਾਲੀਬਾਲ ਦਾ ਦੋਸਤਾਨਾ ਮੈਚ','Curricular Activities','2025-05-30',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Refresh Course for Teachers, Headmistress & Principals of all Akal Academies','ਸਾਰੀਆਂ ਅਕਾਲ ਅਕੈਡਮੀਆਂ ਦੇ ਅਧਿਆਪਕਾਂ, ਹੈੱਡਮਿਸਟ੍ਰੈਸ ਅਤੇ ਪ੍ਰਿੰਸੀਪਲਾਂ ਲਈ ਰਿਫਰੈਸ਼ ਕੋਰਸ','Curricular Activities','2025-06-01',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House Discovery contest','ਇੰਟਰ ਹਾਊਸ ਡਿਸਕਵਰੀ ਮੁਕਾਬਲਾ','Curricular Activities','2025-06-06',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House Atlas Quiz / Mock UN Session','ਇੰਟਰ ਹਾਊਸ ਐਟਲਸ ਕਵਿਜ਼ / ਮੌਕ ਸੰਯੁਕਤ ਰਾਸ਼ਟਰ ਸੈਸ਼ਨ','Curricular Activities','2025-06-13',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House: English Debate /English Poetry  recitation Competition','ਇੰਟਰ ਹਾਊਸ: ਅੰਗਰੇਜ਼ੀ ਬਹਿਸ/ਅੰਗਰੇਜ਼ੀ ਕਵਿਤਾ ਪਾਠ ਮੁਕਾਬਲਾ','Curricular Activities','2025-06-20',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Know your Constitution Week (Programmers in Morning Assembly)','ਆਪਣਾ ਸੰਵਿਧਾਨ ਹਫ਼ਤਾ ਜਾਣੋ (ਸਵੇਰ ਦੀ ਅਸੈਂਬਲੀ ਵਿੱਚ ਪ੍ਰੋਗਰਾਮਰ)','Curricular Activities','2025-06-24',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Ground Activity: Friendly match of Football, Basket Ball, Volley ball','ਗਰਾਊਂਡ ਗਤੀਵਿਧੀ: ਫੁੱਟਬਾਲ, ਬਾਸਕਟ ਬਾਲ, ਵਾਲੀਬਾਲ ਦਾ ਦੋਸਤਾਨਾ ਮੈਚ','Curricular Activities','2025-06-27',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PTM for VI-IX(Boys)','VI-IX (ਲੜਕੇ) ਲਈ PTM','Curricular Activities','2025-05-31',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PTM for VII-IX(Girls)','VII-IX (ਲੜਕੀਆਂ) ਲਈ PTM','Curricular Activities','2025-06-07',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PTM for X-XII(Boys)','X-XII (ਲੜਕੇ) ਲਈ PTM','Curricular Activities','2025-06-14',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PTM for X-XII(Girls)','X-XII (ਲੜਕੀਆਂ) ਲਈ PTM','Curricular Activities','2025-06-21',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Religious programme: Sant Samagam in memory of  Sant Teja Singh ji','ਧਾਰਮਿਕ ਪ੍ਰੋਗਰਾਮ: ਸੰਤ ਤੇਜਾ ਸਿੰਘ ਜੀ ਦੀ ਯਾਦ ਵਿੱਚ ਸੰਤ ਸਮਾਗਮ','Curricular Activities','2025-07-01',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Cyber safety Week  & Inter House: IT  Quiz','ਸਾਈਬਰ ਸੁਰੱਖਿਆ ਹਫ਼ਤਾ ਅਤੇ ਇੰਟਰ ਹਾਊਸ: ਆਈਟੀ ਕਵਿਜ਼','Curricular Activities','2025-07-04',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Religious Programme : Shaheedi Diwas of Bhai Taru Singh ji','ਧਾਰਮਿਕ ਪ੍ਰੋਗਰਾਮ : ਭਾਈ ਤਾਰੂ ਸਿੰਘ ਜੀ ਦਾ ਸ਼ਹੀਦੀ ਦਿਹਾੜਾ','Curricular Activities','2025-07-16',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter house Calligraphy competition.','ਇੰਟਰ ਹਾਊਸ ਕੈਲੀਗ੍ਰਾਫੀ ਮੁਕਾਬਲਾ।','Curricular Activities','2025-07-16',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Club Activity: Go Green – Adopting a hill and making it green : Plantation Drive , Green Planet Wall Magazine','ਕਲੱਬ ਗਤੀਵਿਧੀ: ਗੋ ਗ੍ਰੀਨ - ਇੱਕ ਪਹਾੜੀ ਨੂੰ ਗੋਦ ਲੈਣਾ ਅਤੇ ਇਸਨੂੰ ਹਰਿਆ ਭਰਿਆ ਬਣਾਉਣਾ: ਪਲਾਂਟੇਸ਼ਨ ਡਰਾਈਵ, ਗ੍ਰੀਨ ਪਲੈਨੇਟ ਵਾਲ ਮੈਗਜ਼ੀਨ','Curricular Activities','2025-07-17',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Visual Art – Poster making (Global issues)','ਵਿਜ਼ੂਅਲ ਆਰਟ - ਪੋਸਟਰ ਮੇਕਿੰਗ (ਗਲੋਬਲ ਮੁੱਦੇ)','Curricular Activities','2025-07-24',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Summer Vacation for Nursery- V','ਨਰਸਰੀ- V ਲਈ ਗਰਮੀਆਂ ਦੀਆਂ ਛੁੱਟੀਆਂ','Curricular Activities','2025-08-08',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Summer Vacation for  VI-XII Boys','VI-XII ਲੜਕਿਆਂ ਲਈ ਗਰਮੀਆਂ ਦੀਆਂ ਛੁੱਟੀਆਂ','Curricular Activities','2025-08-08',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Summer Vacation for  VI-XII Girls','VI-XII ਕੁੜੀਆਂ ਲਈ ਗਰਮੀਆਂ ਦੀਆਂ ਛੁੱਟੀਆਂ','Curricular Activities','2025-08-08',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Religious programme: First Prakash Purab of Shri Granth Sahib Ji   Inter House Gurmat Quiz','ਧਾਰਮਿਕ ਪ੍ਰੋਗਰਾਮ: ਸ਼੍ਰੀ ਗ੍ਰੰਥ ਸਾਹਿਬ ਜੀ ਦਾ ਪਹਿਲਾ ਪ੍ਰਕਾਸ਼ ਪੁਰਬ ਅੰਤਰ ਹਾਊਸ ਗੁਰਮਤਿ ਕੁਇਜ਼','Curricular Activities','2025-08-24',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Religious Programme: Guru Granth Sahib ji Sampuranta Divas','ਧਾਰਮਿਕ ਪ੍ਰੋਗਰਾਮ: ਗੁਰੂ ਗ੍ਰੰਥ ਸਾਹਿਬ ਜੀ ਸੰਪੂਰਨਤਾ ਦਿਵਸ','Curricular Activities','2025-08-29',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PTM for for Nursery – V (Girls & Boys)','ਪੀ.ਟੀ.ਐਮ.ਨਰਸਰੀ - V  ਲਈ (ਲੜਕੀਆਂ ਅਤੇ ਮੁੰਡੇ)','Curricular Activities','2025-08-31',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House Radio Show competition','ਇੰਟਰ ਹਾਊਸ ਰੇਡੀਓ ਸ਼ੋਅ ਮੁਕਾਬਲਾ','Curricular Activities','2025-09-04',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Teachers Day Celebration (Champion Teachers.)','ਅਧਿਆਪਕ ਦਿਵਸ ਦਾ ਜਸ਼ਨ (ਚੈਂਪੀਅਨ ਅਧਿਆਪਕ।)','Curricular Activities','2025-09-05',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House: Hindi Dictionary Quiz / Hindi Poetry recitation','ਇੰਟਰ ਹਾਊਸ: ਹਿੰਦੀ ਡਿਕਸ਼ਨਰੀ ਕਵਿਜ਼ / ਹਿੰਦੀ ਕਵਿਤਾ ਪਾਠ','Curricular Activities','2025-09-11',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House Explore Science Competition','ਇੰਟਰ ਹਾਊਸ ਐਕਸਪਲੋਰ ਸਾਇੰਸ ਮੁਕਾਬਲਾ','Curricular Activities','2025-09-19',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Digital Learners Week','ਡਿਜੀਟਲ ਸਿੱਖਿਅਕ ਹਫ਼ਤਾ','Curricular Activities','2025-09-20',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Ground Activity :  Hockey, Volleyball, Basket Ball','ਗਰਾਊਂਡ ਗਤੀਵਿਧੀ: ਹਾਕੀ, ਵਾਲੀਬਾਲ, ਬਾਸਕਟ ਬਾਲ','Curricular Activities','2025-09-26',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Club Activity: Rally on Drug Abuse in Society','ਕਲੱਬ ਗਤੀਵਿਧੀ: ਸਮਾਜ ਵਿੱਚ ਨਸ਼ਿਆਂ ਦੀ ਦੁਰਵਰਤੋਂ ''ਤੇ ਰੈਲੀ','Curricular Activities','2025-09-30',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PTM for VII-IX(Boys)','VII-IX (ਲੜਕੇ) ਲਈ PTM','Curricular Activities','2025-07-07',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PTM for VII-XII(Girls)','VII-XII (ਲੜਕੀਆਂ) ਲਈ PTM','Curricular Activities','2025-09-14',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PTM for X-XII(Boys)','X-XII (ਲੜਕੇ) ਲਈ PTM','Curricular Activities','2025-09-21',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PCM for Nursery – VI (Girls & Boys)','ਨਰਸਰੀ ਲਈ PCM - VI (ਲੜਕੀਆਂ ਅਤੇ ਲੜਕੇ)','Curricular Activities','2025-09-28',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Gandhi Jayanthi','ਗਾਂਧੀ ਜਯੰਤੀ','Curricular Activities','2025-10-02',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House Group Discussion competition','ਇੰਟਰ ਹਾਊਸ ਗਰੁੱਪ ਚਰਚਾ ਮੁਕਾਬਲਾ','Curricular Activities','2025-10-03',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Post Midterm Examination','ਪੋਸਟ ਮਿਡਟਰਮ ਪ੍ਰੀਖਿਆ','Curricular Activities','2025-10-10',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Religious Programme: Parkash Shri Guru Ramdas Ji','ਧਾਰਮਿਕ ਪ੍ਰੋਗਰਾਮ: ਪ੍ਰਕਾਸ਼ ਸ਼੍ਰੀ ਗੁਰੂ ਰਾਮਦਾਸ ਜੀ','Curricular Activities','2025-10-20',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter house Competition (Glimpses of Sikh History)','ਅੰਤਰ ਹਾਊਸ ਮੁਕਾਬਲਾ (ਸਿੱਖ ਇਤਿਹਾਸ ਦੀਆਂ ਝਲਕੀਆਂ)','Curricular Activities','2025-10-20',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Religious  Programme: Bandi Chhod Diwas / Diwali','ਧਾਰਮਿਕ ਪ੍ਰੋਗਰਾਮ: ਬੰਦੀ ਛੋੜ ਦਿਵਸ/ਦੀਵਾਲੀ','Curricular Activities','2025-10-20',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Inter House Speech and Shabad Gayan Competition','ਅੰਤਰ ਹਾਊਸ ਭਾਸ਼ਣ ਅਤੇ ਸ਼ਬਦ ਗਾਇਨ ਮੁਕਾਬਲਾ','Curricular Activities','2025-10-20',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'United Nations Week. (Week long programmes in Morning Assembly)','ਸੰਯੁਕਤ ਰਾਸ਼ਟਰ ਹਫ਼ਤਾ. (ਮੌਰਨਿੰਗ ਅਸੈਂਬਲੀ ਵਿੱਚ ਹਫ਼ਤੇ ਭਰ ਦੇ ਪ੍ਰੋਗਰਾਮ)','Curricular Activities','2025-10-24',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PCM for VII-IX (Boys)','VII-IX (ਲੜਕੇ) ਲਈ PCM','Curricular Activities','2025-10-06',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PCM for VII-XII (Girls)','VII-XII (ਲੜਕੀਆਂ) ਲਈ PCM','Curricular Activities','2025-10-13',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PCM for X-XII(Boys)','X-XII (ਲੜਕੇ) ਲਈ PCM','Curricular Activities','2025-10-20',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Religious Programme: ParkashPurab (Shri Guru Nanak Dev Ji) AkhandPaath by Students and teachers of AABS & Shabad Kirtan Inter House programme.','ਧਾਰਮਿਕ ਪ੍ਰੋਗਰਾਮ: ਪ੍ਰਕਾਸ਼ ਪੁਰਬ (ਸ਼੍ਰੀ ਗੁਰੂ ਨਾਨਕ ਦੇਵ ਜੀ) AABS ਅਤੇ ਸ਼ਬਦ ਕੀਰਤਨ ਇੰਟਰ ਹਾਊਸ ਪ੍ਰੋਗਰਾਮ ਦੇ ਵਿਦਿਆਰਥੀਆਂ ਅਤੇ ਅਧਿਆਪਕਾਂ ਦੁਆਰਾ ਅਖੰਡਪਾਠ।','Curricular Activities','2025-11-05',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'PYP Exhibition, Art Fest','PYP ਪ੍ਰਦਰਸ਼ਨੀ, ਆਰਟ ਫੈਸਟ','Curricular Activities','2025-11-07',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Annual Day for Nur-XII','ਨਰਸਰੀ ਤੋਂ ਕਲਾਸ XII ਤੱਕ ਲਈ ਸਲਾਨਾ ਦਿਵਸ','Curricular Activities','2025-11-08',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Disaster Management Week','ਆਫ਼ਤ ਪ੍ਰਬੰਧਨ ਹਫ਼ਤਾ','Curricular Activities','2025-11-10',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Children day &  Sports Day','ਬਾਲ ਦਿਵਸ ਅਤੇ ਖੇਡ ਦਿਵਸ','Curricular Activities','2025-11-14',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Submission of Answer sheets','ਉੱਤਰ ਪੱਤਰੀਆਂ ਜਮ੍ਹਾਂ ਕਰਾਉਣੀਆਂ','Curricular Activities','2025-12-21',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Result Compilation and  Declaration','ਨਤੀਜਾ ਸੰਕਲਨ ਅਤੇ ਘੋਸ਼ਣਾ','Curricular Activities','2025-12-22',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Record Entry, Reflection Day & Preparation for next session','ਰਿਕਾਰਡ ਐਂਟਰੀ, ਰਿਫਲਿਕਸ਼ਨ ਡੇਅ ਅਤੇ ਅਗਲੇ ਸੈਸ਼ਨ ਦੀ ਤਿਆਰੀ','Curricular Activities','2025-12-23',0);
INSERT INTO issue_tracker_activity_calender(school_id,title,title_punjabi,type,suggested_date,is_holiday) VALUES (130,'Dispatching of report cards','ਰਿਪੋਰਟ ਕਾਰਡਾਂ ਦੀ ਵੰਡ','Curricular Activities','2025-12-24',0);

ALTER TABLE pp_school_notification 
ADD COLUMN heading_punjabi VARCHAR(255) CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL AFTER heading,
ADD COLUMN description_punjabi TEXT CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL AFTER message;

-- For student notifications table
ALTER TABLE pp_std_notification 
ADD COLUMN heading_punjabi VARCHAR(255) CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL AFTER heading,
ADD COLUMN description_punjabi TEXT CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL AFTER message;

-- Update character set for existing columns
ALTER TABLE pp_school_notification 
MODIFY heading_punjabi VARCHAR(255) CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL,
MODIFY description_punjabi TEXT CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL;

ALTER TABLE pp_std_notification
MODIFY heading_punjabi VARCHAR(255) CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL,
MODIFY description_punjabi TEXT CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL;
