UPDATE `students2024-25` SET first_name = 'SEHAJDEEP', last_name = 'KAUR' WHERE school_id = 61 AND admission_no = 1930;
UPDATE `students2024-25` SET first_name = 'MANVIR', last_name = 'SINGH' WHERE school_id = 61 AND admission_no = 2433;
UPDATE `students2024-25` SET first_name = 'MANVEER', last_name = 'SINGH' WHERE school_id = 61 AND admission_no = 2388;
UPDATE `students2024-25` SET first_name = 'GURNOOR', last_name = 'SINGH SEKHON' WHERE school_id = 61 AND admission_no = 2417;
UPDATE `students2024-25` SET first_name = 'MANRAJ', last_name = 'SINGH DHILLON' WHERE school_id = 61 AND admission_no = 2395;
UPDATE `students2024-25` SET first_name = 'JUJHAR', last_name = 'SINGH DHILLON' WHERE school_id = 61 AND admission_no = 2405;
UPDATE `students2024-25` SET first_name = 'GAJINDER', last_name = 'SINGH BENIPAL' WHERE school_id = 61 AND admission_no = 2390;
UPDATE `students2024-25` SET first_name = 'GURNOOR', last_name = 'SINGH SANDHU' WHERE school_id = 61 AND admission_no = 2403;
UPDATE `students2024-25` SET first_name = 'AKASHVIR', last_name = 'SINGH' WHERE school_id = 61 AND admission_no = 2407;
UPDATE `students2024-25` SET first_name = 'PRABHJOT', last_name = 'SINGH' WHERE school_id = 61 AND admission_no = 2146;
UPDATE `students2024-25` SET first_name = 'JAPNEET', last_name = 'KAUR CHAUHAN' WHERE school_id = 61 AND admission_no = 2619;
UPDATE `students2024-25` SET first_name = 'ANSH', last_name = 'BHANJOT' WHERE school_id = 61 AND admission_no = 2419;
UPDATE `students2024-25` SET first_name = 'AVNEET', last_name = 'KAUR' WHERE school_id = 61 AND admission_no = 2441;
UPDATE `students2024-25` SET first_name = 'DARPANJOT', last_name = 'SINGH DHADLY' WHERE school_id = 61 AND admission_no = 2541;
UPDATE `students2024-25` SET first_name = 'SATINDER', last_name = 'KUMAR' WHERE school_id = 61 AND admission_no = 3160;
UPDATE `students2024-25` SET first_name = 'RANVIR', last_name = 'SINGH' WHERE school_id = 61 AND admission_no = 2224;
UPDATE `students2024-25` SET first_name = 'SHARANJEET', last_name = 'SINGH AUJLA' WHERE school_id = 61 AND admission_no = 2194;
UPDATE `students2024-25` SET first_name = 'AGAMPREET', last_name = 'SINGH BENIPAL' WHERE school_id = 61 AND admission_no = 2148;
UPDATE `students2024-25` SET first_name = 'GURSHAN', last_name = 'SINGH GILL' WHERE school_id = 61 AND admission_no = 2434;
UPDATE `students2024-25` SET first_name = 'ARLEEN', last_name = 'KAUR' WHERE school_id = 61 AND admission_no = 2853;
UPDATE `students2024-25` SET first_name = 'PRABHJOT', last_name = 'SINGH GARCHA' WHERE school_id = 61 AND admission_no = 2161;
UPDATE `students2024-25` SET first_name = 'HARMANPREET', last_name = 'KAUR MANGAT' WHERE school_id = 61 AND admission_no = 2197;
UPDATE `students2024-25` SET first_name = 'HARGUN', last_name = 'KAUR DHANDA' WHERE school_id = 61 AND admission_no = 2926;
UPDATE `students2024-25` SET first_name = 'HARSHDEEP', last_name = 'SINGH' WHERE school_id = 61 AND admission_no = 2827;
UPDATE `students2024-25` SET first_name = 'JUGRAJ', last_name = 'SINGH RAI' WHERE school_id = 61 AND admission_no = 2340;
UPDATE `students2024-25` SET first_name = 'MANJOT', last_name = 'KAUR DHILLON' WHERE school_id = 61 AND admission_no = 2394;
UPDATE `students2024-25` SET first_name = 'MANPREET', last_name = 'SINGH GILL' WHERE school_id = 61 AND admission_no = 2821;
UPDATE `students2024-25` SET first_name = 'PRABHNOOR', last_name = 'SINGH DHALIWAL' WHERE school_id = 61 AND admission_no = 2803;
UPDATE `students2024-25` SET first_name = 'GURSAAJ', last_name = 'SINGH NAGRA' WHERE school_id = 61 AND admission_no = 2811;
UPDATE `students2024-25` SET first_name = 'ARMAAN', last_name = 'SINGH BILLING' WHERE school_id = 61 AND admission_no = 2838;
UPDATE `students2024-25` SET first_name = 'ABHAJOT', last_name = 'SINGH KANG' WHERE school_id = 61 AND admission_no = 2933;
UPDATE `students2024-25` SET first_name = 'GURLAL', last_name = 'SINGH BHANGU' WHERE school_id = 61 AND admission_no = 2916;
UPDATE `students2024-25` SET first_name = 'HARLEEN', last_name = 'KAUR BENIPAL' WHERE school_id = 61 AND admission_no = 2143;
UPDATE `students2024-25` SET first_name = 'ARSHDEEP', last_name = 'SINGH BATTH' WHERE school_id = 61 AND admission_no = 2141;
UPDATE `students2024-25` SET first_name = 'JASMANAT', last_name = 'SINGH MAAN' WHERE school_id = 61 AND admission_no = 2185;
UPDATE `students2024-25` SET first_name = 'JASHANPREET', last_name = 'KAUR' WHERE school_id = 61 AND admission_no = 2019;
UPDATE `students2024-25` SET first_name = 'GURADESH', last_name = 'SINGH KHAIRA' WHERE school_id = 61 AND admission_no = 2260;
UPDATE `students2024-25` SET first_name = 'KARANVIR', last_name = 'SINGH' WHERE school_id = 61 AND admission_no = 2548;
UPDATE `students2024-25` SET first_name = 'SHUBHKARMAN', last_name = 'KAUR' WHERE school_id = 61 AND admission_no = 2920;
UPDATE `students2024-25` SET first_name = 'TARANVEER', last_name = 'SINGH' WHERE school_id = 61 AND admission_no = 2628;
UPDATE `students2024-25` SET first_name = 'JASMEEN', last_name = 'KAUR' WHERE school_id = 61 AND admission_no = 2512;
UPDATE `students2024-25` SET first_name = 'HARSHPREET', last_name = 'KAUR' WHERE school_id = 61 AND admission_no = 2306;
UPDATE `students2024-25` SET first_name = 'JASKARAN', last_name = 'SINGH' WHERE school_id = 61 AND admission_no = 2190;
UPDATE `students2024-25` SET first_name = 'MANVEER', last_name = 'SINGH' WHERE school_id = 61 AND admission_no = 2239;
UPDATE `students2024-25` SET first_name = 'ARSHDEEP', last_name = 'KAUR' WHERE school_id = 61 AND admission_no = 2247;
UPDATE `students2024-25` SET first_name = 'MANVINDER', last_name = 'SINGH DHINDSA' WHERE school_id = 61 AND admission_no = 3166;
UPDATE `students2024-25` SET first_name = 'MEHAKDEEP', last_name = 'KAUR' WHERE school_id = 61 AND admission_no = 2587;
UPDATE `students2024-25` SET first_name = 'TARANVEER', last_name = 'SINGH ADOL' WHERE school_id = 61 AND admission_no = 3031;
UPDATE `students2024-25` SET first_name = 'TARANJIT', last_name = 'KAUR' WHERE school_id = 61 AND admission_no = 2131;
UPDATE `students2024-25` SET first_name = 'SIMRANPREET', last_name = 'KAUR SHERGILL' WHERE school_id = 61 AND admission_no = 2179;
UPDATE `students2024-25` SET first_name = 'MANJOT', last_name = 'KAUR TIWANA' WHERE school_id = 61 AND admission_no = 2290;
UPDATE `students2024-25` SET first_name = 'PAWANDEEP', last_name = 'SINGH TIWANA' WHERE school_id = 61 AND admission_no = 2289;
UPDATE `students2024-25` SET first_name = 'JASMAN', last_name = 'SEKHON' WHERE school_id = 61 AND admission_no = 2526;
UPDATE `students2024-25` SET first_name = 'PRABHPREET', last_name = 'SINGH' WHERE school_id = 61 AND admission_no = 2282;
UPDATE `students2024-25` SET first_name = 'ARMAAN', last_name = 'SINGH DHANDA' WHERE school_id = 61 AND admission_no = 2814;
UPDATE `students2024-25` SET first_name = 'GURWINDER', last_name = 'SINGH DHILLON' WHERE school_id = 61 AND admission_no = 2843;
UPDATE `students2024-25` SET first_name = 'HARSEHAJ', last_name = 'SINGH GREWAL' WHERE school_id = 61 AND admission_no = 2830;
UPDATE `students2024-25` SET first_name = 'ABHINOOR', last_name = 'KAUR PANAICH' WHERE school_id = 61 AND admission_no = 3250;
UPDATE `students2024-25` SET first_name = 'GURFATHEH', last_name = 'SINGH' WHERE school_id = 61 AND admission_no = 3011;